# Generated by Django 5.2.5 on 2025-09-06 02:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_alter_paciente_options_remove_paciente_usuario_and_more'),
        ('turnos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='turno',
            constraint=models.UniqueConstraint(fields=('agenda', 'fecha_hora'), name='unique_turno_agenda_fecha'),
        ),
    ]
