# Generated by Django 5.2.5 on 2026-03-02 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialidad',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
    ]
