# Generated by Django 5.2.5 on 2025-09-05 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Secretaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateField()),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('tiene_licencia', models.BooleanField(default=False)),
                ('fecha_inicio_licencia', models.DateField(blank=True, null=True)),
                ('fecha_fin_licencia', models.DateField(blank=True, null=True)),
                ('suplente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suplencias', to='secretarias.secretaria')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='secretaria', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
