# Generated by Django 5.2.5 on 2025-09-05 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretarias', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='secretaria',
            old_name='fecha_fin_licencia',
            new_name='fecha_nac',
        ),
        migrations.RemoveField(
            model_name='secretaria',
            name='fecha_inicio_licencia',
        ),
        migrations.RemoveField(
            model_name='secretaria',
            name='suplente',
        ),
        migrations.RemoveField(
            model_name='secretaria',
            name='tiene_licencia',
        ),
        migrations.AddField(
            model_name='secretaria',
            name='documento',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.CreateModel(
            name='Licencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('VAC', 'Vacaciones'), ('MED', 'Licencia Médica'), ('PER', 'Permiso Especial'), ('OTR', 'Otra')], default='VAC', max_length=3)),
                ('periodo', models.PositiveIntegerField(help_text='Año al que corresponde la licencia')),
                ('dias_totales', models.PositiveIntegerField(default=0)),
                ('dias_tomados', models.PositiveIntegerField(default=0)),
                ('dias_pendientes', models.PositiveIntegerField(default=0)),
                ('fecha_inicio_licencia', models.DateField(blank=True, null=True)),
                ('fecha_fin_licencia', models.DateField(blank=True, null=True)),
                ('secretaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licencias', to='secretarias.secretaria')),
                ('suplente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suplencias', to='secretarias.secretaria')),
            ],
        ),
    ]
