# Generated by Django 5.2.5 on 2025-09-05 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretarias', '0002_rename_fecha_fin_licencia_secretaria_fecha_nac_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licencia',
            name='dias_pendientes',
        ),
        migrations.RemoveField(
            model_name='licencia',
            name='dias_tomados',
        ),
        migrations.CreateModel(
            name='TramoLicencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('dias_tomados', models.PositiveIntegerField(blank=True, help_text='Ingrese la cantidad real de días computables (excluyendo fines de semana y feriados)', null=True)),
                ('licencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tramos', to='secretarias.licencia')),
            ],
        ),
    ]
