# Generated by Django 5.2.5 on 2025-09-05 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paciente',
            options={'ordering': ['apellido', 'nombre'], 'verbose_name': 'Paciente', 'verbose_name_plural': 'Pacientes'},
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='usuario',
        ),
        migrations.AddField(
            model_name='paciente',
            name='apellido',
            field=models.CharField(default='Sin Apellido', max_length=100),
        ),
        migrations.AddField(
            model_name='paciente',
            name='nombre',
            field=models.CharField(default='Sin Nombre', max_length=100),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='documento',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
